services:
  - type: web
    name: electrical-shop
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn electrical_shop.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: electrical-shop-db
          property: connectionString

databases:
  - name: electrical-shop-db
    plan: free
